In [8]:
import numpy as np

array = np.random.rand(10,10)

a = np.diag(np.diag(array))

print("Diagnoal Values : \n", res); 

Diagnoal Values : 
 [[0.26993447 0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.65153901 0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.48607329 0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.9748672  0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.40558278 0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.29528408
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.89292274 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.01932287 0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.64670064 0.        ]
 [0.     

In [11]:
import numpy as np

array = np.random.rand(4,4)

a = np.triu(array)

print("Diagnoal Values : \n", a); 

Diagnoal Values : 
 [[0.53448368 0.50371136 0.60703122 0.34732721]
 [0.         0.90184324 0.53584118 0.97612134]
 [0.         0.         0.22363835 0.84056478]
 [0.         0.         0.         0.32040381]]


In [12]:
import numpy as np

array = np.random.rand(4,4)

a = np.tril(array)

print("Diagnoal Values : \n", a); 

Diagnoal Values : 
 [[0.86468465 0.         0.         0.        ]
 [0.29106757 0.6445199  0.         0.        ]
 [0.61094288 0.5732106  0.24009884 0.        ]
 [0.64829315 0.97093717 0.27689521 0.82022324]]
