In [2]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [7]:
a = np.array(range(16))
print(a, a.dtype)

print()
a = np.array([1,2,3,4.5], dtype = 'int32', ndmin = 2)
print(a, a.dtype)
print('itemsize', a.itemsize, a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] int32

[[1 2 3 4]] int32
itemsize 4 (1, 4)


In [8]:
34421

34421

In [10]:
a = np.arange(10,19)
print(a)

a1 = a.reshape(3,3)
print(a1)

[10 11 12 13 14 15 16 17 18]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [11]:
a = np.arange(10,19,2)
print(a, "  ", a.mean(), "  ",a.min(), "  ",a.max(), "  ",a.sum())

[10 12 14 16 18]    14.0    10    18    70


In [20]:
a = np.arange(0,24).reshape(4,6)
print(a)
print(a.min(), a.max())
print(a.min(axis = 0), a.max(axis = 0))
print(a.min(axis = 1), a.max(axis = 1))

# axis = 0 for row and axis = 1 for column

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
0 23
[0 1 2 3 4 5] [18 19 20 21 22 23]
[ 0  6 12 18] [ 5 11 17 23]


In [24]:
a = np.random.randint(10,20,100).reshape(10,10)
print(a)

a = np.zeros(10)
print(a)

[[14 18 12 19 12 10 10 16 10 18]
 [15 19 16 12 12 10 11 10 19 10]
 [10 15 15 17 13 16 18 11 10 10]
 [16 18 16 12 19 15 13 17 19 17]
 [17 14 19 12 18 11 18 11 18 15]
 [17 18 15 11 12 19 10 14 13 18]
 [15 13 15 13 13 10 10 15 17 12]
 [18 16 17 10 10 19 11 17 13 11]
 [16 16 11 15 13 15 10 15 14 17]
 [19 14 18 15 12 12 10 18 16 11]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Indexing and slicing

In [28]:
a = np.arange(12).reshape(4,3)
print(a)

print(a[1])
print(a[1,0])
print()
print(a[1:3])
print(a[1:3, 1:])

print(np.linspace(10,20,20, dtype = 'int8'))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[3 4 5]
3

[[3 4 5]
 [6 7 8]]
[[4 5]
 [7 8]]
[10 10 11 11 12 12 13 13 14 14 15 15 16 16 17 17 18 18 19 20]


In [32]:
a = np.arange(12).reshape(4,3)
print(a)
print()

print(a [(0,2)])
print()

print(a[(0,2) , (1,2)])
print()

print(a[:, (0,2)])
print()

print(a[True, True, False, True])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

2

[1 8]

[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]

[]


In [33]:

a = np.arange(10,20)
a2 = np.arange(20,10,-1)
print(a, a2)
print(a * 2)
print(a * a2)

print()
res = (a %2 == 0)
print(res)
print(a[res])

print()
res = (a %3 == 0) | (a%5 == 0)
print(res)
print(a[res])

print()
res = (a %3 == 0) & (a%5 == 0)
print(res)
print(a[res])

[10 11 12 13 14 15 16 17 18 19] [20 19 18 17 16 15 14 13 12 11]
[20 22 24 26 28 30 32 34 36 38]
[200 209 216 221 224 225 224 221 216 209]

[ True False  True False  True False  True False  True False]
[10 12 14 16 18]

[ True False  True False False  True False False  True False]
[10 12 15 18]

[False False False False False  True False False False False]
[15]
