In [3]:
# Write a Python program to print the NumPy version in your system.

import numpy as np
print(np.__version__)

1.17.3


In [6]:
# Write a Python program to reverse an array (first element becomes last).

arr = np.arange(10)
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [11]:
# Write a Python program to convert a list and tuple into arrays

lst = np.array([3,4,5])
tp = ('Rahul', 'Kumar', 1,2)
tp2 = np.asarray(tp)
print(lst)
print(tp2)

[3 4 5]
['Rahul' 'Kumar' '1' '2']


In [1]:
# Write a program to find common values between two arrays

import numpy as np
arr1 = [1,2,3,4,5]
arr2 = [2,3,4,5,6,7,8]
print(np.intersect1d(arr1,arr2))

[2 3 4 5]


In [6]:
# Write a Python program compare two arrays using numpy.
import numpy as np

print(np.array_equal([1,2],[1,2]))

arr1 = np.arange(5)
arr2 = np.arange(5)

print(arr1, arr2)

np.array_equal(arr1, arr2)

True
[0 1 2 3 4] [0 1 2 3 4]


True

In [15]:
# Write a Python program to change the dimension of an array.

arr3 = np.arange(10)
print(arr3)
np.resize(arr3,(1,8))

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [2]:
# Write a Python program (using numpy) to sum of all the multiples of 3 or 5 below 100.

import numpy as np
x = np.arange(1,100)
num = x[(x % 3 == 0)| (x % 5 == 0)]
print(num.sum())

2318


In [3]:
# Write a Python program to convert a NumPy array into Python list structure.

import numpy as np
x = np.arange(6).reshape(3,2)
print(x.tolist())

[[0, 1], [2, 3], [4, 5]]


In [5]:
# Write a Python program to how to add an extra column to a numpy array.

import numpy as np
x = np.array([1,2,3,4])
y = np.array([5,6])
print(np.append(x,y,axis = 0))

[1 2 3 4 5 6]


In [7]:
# Write a Python program to check whether the numpy array is empty or not.

import numpy as np
arr = np.array([])
print(arr.size)

0


In [ ]:
# Write a Python program to normalize a 3x3 random matrix.



In [ ]:
# How to ignore all numpy warnings (not recommended)?

# numpy.testing.suppress_warnings

In [13]:
# How to swap two rows of an array?

arr1 = np.array([[1,2,3,4],[5,6,7,8],[11,22,33,44],[55,66,77,88]])
arr1[[0,2]] = arr1[[2,0]]
print(arr1)

[[11 22 33 44]
 [ 5  6  7  8]
 [ 1  2  3  4]
 [55 66 77 88]]


In [30]:
# Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).



In [29]:
# Python program to create a random vector of size 10 and sort it.

import numpy as np
arr = np.random.rand(10)
arr.sort()
print(arr)

[0.11226502 0.13833848 0.15980775 0.17708557 0.1993508  0.28771018
 0.54863104 0.58609    0.6200923  0.87342445]


In [32]:
# Write a Python program to check two random arrays are equal or not.

a = np.random.randint(0,2,6)
b = np.random.randint(0,2,6)
print(a,b)
result = np.allclose(a,b)
print(result)

[0 0 0 1 0 0] [1 0 1 0 0 1]
False


In [33]:
# Write a Python program to add, subtract, multiply, divide arguments element-wise.

print(np.add(10,20))
print(np.subtract(10,20))
print(np.multiply(10,20))
print(np.divide(10,20))

30
-10
200
0.5


In [20]:
# Write a Python program to get the dates of yesterday, today and tomorrow.

import datetime

today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1)
print(yesterday)
print(today)
print(tomorrow)

2020-05-09
2020-05-10
2020-05-11
